INDEX:   &INDEX ${UKWA_INDEX}
ARCHIVE: &ARCHIVE ${UKWA_ARCHIVE}

collections:
    # reading room collection (locks and blocks only)
    reading-room:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        single-use-lock: true
        acl_paths:
            - ./acl/blocks.aclj

    # open access (with access controls)
    open-access:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        acl_paths:
            - ./acl/blocks.aclj
            - ./acl/allows.aclj

        default_access: block

    # QA no access controls
    qa-access:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

proxy:
    # collection for proxy mode
    coll: qa-access
    ca_name: UKWA pywb HTTPS Proxy CA
    ca_file_cache: ./proxy-certs/pywb-ca.pem


locales_root_dir: ./i18n/translations/
locales:
  - en
  - cy

