INDEX:   &INDEX ${UKWA_INDEX}
ARCHIVE: &ARCHIVE ${UKWA_ARCHIVE}

collections:
    # reading room collection (locks and blocks only)
    reading-room:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        single-use-lock: true
        acl_paths:
            - ./acl/blocks.aclj

    # open access (with access controls)
    open-access:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        acl_paths:
            - ./acl/blocks.aclj
            - ./acl/allows.aclj

        default_access: block

    # open access (with access controls) under /archive/
    archive:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        acl_paths:
            - ./acl/blocks.aclj
            - ./acl/allows.aclj

        default_access: block

    # QA no access controls
    qa-access:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

    # QA no access controls
    vid-qa:
        index_group:
          qa: *INDEX
          vidtest: collections/video-test/indexes

        archive_paths:
          - *ARCHIVE
          - collections/video-test/archive/



proxy:
    # collection for proxy mode
    coll: qa-access
    ca_name: UKWA pywb HTTPS Proxy CA
    ca_file_cache: ./proxy-certs/pywb-ca.pem


# redirect to exact url behavior
redirect_to_exact: true

# enable memento
enable_memento: true

# enable experimental Memento Prefer
enable_prefer: true


# enable new video transclusions
transclusions_version: 2

# i18n
locales_root_dir: ./i18n/translations/
locales:
  - en
  - cy

