version: '2'

services:

  cdx:
    image: ukwa/tinycdxserver:ukwa-production
    ports:
      - "9090:8080"
  
  hadoop:
    build: ./hadoop/
    command: "/etc/bootstrap.sh -d"
    ports:
      - "50070:50070"
      - "50075:50075"
    hostname: hadoop

  owb:
    image: ukwa/waybacks
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=qa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://hadoop:50070/webhdfs/v1/"
      - "CDX_INDEX_SERVER=http://cdx:8080/tc"
      - "WAYBACK_URL_PREFIX=http://localhost:8080"
      - "WAYBACK_URL_HOST=localhost" 

  populate:
    image: sequenceiq/alpine-curl
    command: /test-data/populate.sh
    volumes:
      - ./test-data/:/test-data

  redis:
    image: redis:3.2.4

  pywb:
    #image: ukwa/pywb
    command: python /ukwa_pywb/ratelimitapp.py --debug
    build: ../
    volumes:
      #- ./pywb:/webarchive
      - ./pywb/config.yaml:/webarchive/config.yaml

    environment:
      - "WEBHDFS_USER=hadoop"
      - "REDIS_URL=redis://redis:6379/0"
      - "SESSION_LOCK_INTERVAL=30"

    ports:
      - "8081:8080"

    depends_on:
      - cdx
      - hadoop
      - redis

# -----------------------------------------------------------
# Automated test engine
# -----------------------------------------------------------

  test:
    build: robot
    #command: -v BROWSER:ff --outputdir /out /tests
    command: --outputdir /out /tests
    volumes:
      - ./robot/tests:/tests:ro
      - ./results/locktest:/out:rw
    depends_on:
      - pywb
      - firefox
      - chrome
      - hub

  firefox:
    image: selenium/node-firefox:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.9.1-actinium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.9.1-actinium
    ports:
      - "4444:4444"

